### 1.3 배열의 연산(Operation)

In [1]:
import numpy as np

- 벡터화 연산

In [2]:
x = np.arange(1, 100001)
y = np.arange(100001, 200001)

In [7]:
%%time
z = np.empty_like(x)
for i in range(100000):
    z[i] = x[i] + y[i]

CPU times: total: 46.9 ms
Wall time: 53 ms


In [9]:
%time z = x + y

CPU times: total: 0 ns
Wall time: 0 ns


In [10]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])
a == b

array([False,  True, False,  True])

In [11]:
a >= b

array([False,  True,  True,  True])

In [12]:
np.exp(a)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [13]:
10 ** a

array([   10,   100,  1000, 10000], dtype=int32)

In [14]:
5 * a

array([ 5, 10, 15, 20])

In [15]:
5 + a

array([6, 7, 8, 9])

- 차원 축소 연산

In [16]:
x = np.arange(1, 5)
np.sum(x)

10

In [17]:
x.sum()

10

In [18]:
x.min(), x.max(), x.mean()      # 최소, 최대, 평균

(1, 4, 2.5)

In [19]:
# 대표값: 평균, 중앙값
np.mean(x), np.median(x)

(2.5, 2.5)

In [20]:
# 통계: 분산, 표준편차
np.var(x), np.std(x)

(1.25, 1.118033988749895)

In [21]:
# 최소값, 최대값의 인덱스
x.argmin(), x.argmax()

(0, 3)

- all / any

In [22]:
np.all(np.array([True, True, False])), np.any(np.array([True, True, False]))

(False, True)

In [23]:
np.all(a == a)

True

- 2차원 이상의 연산

In [24]:
a = np.arange(1, 7).reshape(2, 3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
# 모든 원소의 합과 평균
np.sum(a), np.mean(a)

(21, 3.5)

In [27]:
# axis = 0, 각 좌표(row, col)에서 row를 변경시켜가면서 액세스
np.sum(a, axis=0), np.mean(a, axis=0)

(array([5, 7, 9]), array([2.5, 3.5, 4.5]))

In [28]:
# axis = 1, 각 좌표(row, col)에서 col을 변경시켜가면서 액세스
np.sum(a, axis=1), np.mean(a, axis=1)

(array([ 6, 15]), array([2., 5.]))

In [29]:
b = np.arange(1, 13).reshape(2, 2, -1)
b

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [30]:
np.sum(b, axis=0)

array([[ 8, 10, 12],
       [14, 16, 18]])

In [31]:
np.sum(b, axis=1)

array([[ 5,  7,  9],
       [17, 19, 21]])

In [32]:
np.sum(b, axis=2)

array([[ 6, 15],
       [24, 33]])

- 연습문제 3.3.1

In [37]:
np.random.seed = 2023
x = np.round(np.random.random(30).reshape(5, 6) * 10, 4)
x

array([[3.2928, 6.28  , 8.4153, 3.6599, 6.953 , 1.1849],
       [3.1454, 3.288 , 4.4191, 6.3   , 5.5182, 8.3204],
       [0.8567, 9.6588, 4.7718, 7.4431, 0.4424, 6.331 ],
       [6.2556, 5.1383, 8.3188, 2.9066, 6.8753, 5.0473],
       [4.5515, 2.4588, 4.795 , 2.2791, 2.9257, 7.8799]])

In [38]:
# 1. 전체의 최댓값
np.max(x)

9.6588

In [39]:
# 2. 각 행의 합
np.sum(x, axis=1)

array([29.7859, 30.9911, 29.5038, 34.5419, 24.89  ])

In [40]:
# 3. 각 행의 최댓값
np.max(x, axis=1)

array([8.4153, 8.3204, 9.6588, 8.3188, 7.8799])

In [41]:
# 4. 각 열의 평균
np.mean(x, axis=0)

array([3.6204 , 5.36478, 6.144  , 4.51774, 4.54292, 5.7527 ])

In [42]:
# 5. 각 열의 최솟값
np.min(x, axis=0)

array([0.8567, 2.4588, 4.4191, 2.2791, 0.4424, 1.1849])

- 정렬(sort)

In [43]:
a = np.array([[4,  3,  5,  7],
              [1, 12, 11,  9],
              [2, 15,  1, 14]])
a

array([[ 4,  3,  5,  7],
       [ 1, 12, 11,  9],
       [ 2, 15,  1, 14]])

In [44]:
np.sort(a)      # default axis=1

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

In [45]:
np.sort(a, axis=0)

array([[ 1,  3,  1,  7],
       [ 2, 12,  5,  9],
       [ 4, 15, 11, 14]])

In [47]:
# 내림차순 정렬, axis=1인 경우
np.sort(a, axis=1)[:, ::-1]

array([[ 7,  5,  4,  3],
       [12, 11,  9,  1],
       [15, 14,  2,  1]])

In [48]:
# 내림차순 정렬, axis=0인 경우
np.sort(a, axis=0)[::-1, :]

array([[ 4, 15, 11, 14],
       [ 2, 12,  5,  9],
       [ 1,  3,  1,  7]])

In [49]:
# sort()는 자기 파괴적(in-place) method
a.sort(axis=1)

In [50]:
a

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

In [52]:
a = np.array([42, 38, 12, 25])
j = np.argsort(a)
j

array([2, 3, 1, 0], dtype=int64)

In [53]:
a[j]

array([12, 25, 38, 42])

- 연습문제 3.3.2

In [51]:
score = np.array([[1,2,3,4],            # 학번
                  [46,99,100,71],       # 영어
                  [81,59,90,100]])      # 수학
score

array([[  1,   2,   3,   4],
       [ 46,  99, 100,  71],
       [ 81,  59,  90, 100]])